version: '3.6'
services:
  db:
    image: postgres
    container_name: phonebook-docker-db
    environment: 
      POSTGRES_PASSWORD: simeon
      POSTGRES_USER: postgres
      POSTGRES_DB: phonebook
    ports:
      - 5432:5432
    networks:
      - backdb
    expose: 
      - 5432

  back:
    build:
      context: .
    image: simeon/phonebook-back
    container_name: phonebook-back
    ports: 
      - 8080:8080
    depends_on: 
      - db
    environment:
      - spring.profiles.active=dev
    networks: 
      - backdb

networks: 
  backdb:
     driver: bridge